---
title: "Lab8"
output: pdf_document
date: "2023-04-11"
---

```{r setup, include=FALSE}
library(tidyverse)
library(haven)
library(sandwich)
library(rdrobust)
library(rpart)
library(randomForest)

dat <- read_dta("health.dta")
view(dat)
```


```{r q1}

#Q1: Creating 10/90 training/test data set

#Set seed
HUID <- 21519588
set.seed(HUID)

#Store health variables from time t-1 which all end with _tm
all_predictors <- colnames(dat[,grep("^[tm1]", names(dat))])
all_predictors

#Store predictor variables which all start with P_*, but EXCLUDE race
race <- c("tm1_dem_black")
exclude_race <- setdiff(all_predictors,race)
exclude_race

#Define training and test data sets
#Use a uniformly distributed random number between 0 and 1
dat$random_number <- runif(length(dat$patient_id))

## Generate a training flag for 10% of the sample
dat$train_flag <- ifelse(dat$random_number<= 0.1, 1, 0) 

#Report number of observations in training and test samples
sum(dat$train_flag)
sum(1-dat$train_flag)

#Data frame with training data (randomly selected 10% of the data)
training <- subset(dat, train_flag == 1)
summary(training)

#Data frame with test data (remaining 90% of the data)
test <- subset(dat, train_flag == 0)
summary(test)





```



```{r q2}

#Q2: Estimating random forest models using the training data set

#2A: random forest model predicting patient costs, excluding race
mod1 <- randomForest(reformulate(exclude_race, "cost_t"), 
                     ntree=100, 
                     mtry=149,
                     importance=TRUE,
                     data=training)
mod1

### generate predictions for all observations in test and training samples
y_test_predictions_mod1 <- predict(mod1, newdata=test)
y_train_predictions_mod1 <- predict(mod1, newdata=training)

#Variable importance
importance(mod1)
varImpPlot(mod1, type=1) #Plot the Random Forest Results
dev.copy(png,'mod1_importance.png')
dev.off()


#(1=mean decrease in accuracy, 2=mean decrease in node impurity)



#2B: random forest model predicting patient costs, including race



#2C: random forest model predicting patient health, excluding race


#2D: random forest model predicting patient health, including race







```



